# Generated by Django 6.0.6 on 2026-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('foto', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
